version: '3.9'

services:
  mendel-app:
    build: .
    container_name: mendel-spa
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mendel.rule=Host(`mendel.local`)"
      - "traefik.http.routers.mendel.entrypoints=web"
      - "traefik.http.services.mendel.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
