#!/usr/bin/env python3
# make_metrics_table.py
import glob, numpy as np, pandas as pd
from pathlib import Path
from sklearn.linear_model import LinearRegression

def part_a():
    df = pd.read_csv("strict_matching_mle.csv")
    mae = np.mean(np.abs(df["true_q"] - df["estimated_q"]))
    return mae

def part_b():
    rows = []
    for fn in sorted(glob.glob("gen_matching_*.csv")):
        df = pd.read_csv(fn)
        X = df[["log_q_ratio"]].values
        y = df["log_odds"].values
        reg = LinearRegression().fit(X, y)
        slope, intercept = reg.coef_[0], reg.intercept_
        # parse beta/bias from filename
        name = Path(fn).stem  # gen_matching_beta1p0_bias0p0
        meta = dict(x.split("beta")[-1].split("_bias"))
        # Fallback if parsing fails
        try:
            beta = float(meta[0].replace("p","."))
            bias = float(meta[1].replace("p","."))
        except Exception:
            beta = np.nan; bias = np.nan
        rows.append((fn, beta, bias, slope, intercept))
    return rows

def part_c():
    # need stream to find switch point
    stream = pd.read_csv("gestalt_stream.csv")
    switch_t = (stream["true_q"] != stream["true_q"].iloc[0]).idxmax() + 1
    target = stream["true_q"].iloc[-1]
    rows = []
    for fn in sorted(glob.glob("gestalt_window_W*.csv")):
        df = pd.read_csv(fn)
        W = int(df["W"].iloc[0])
        df_after = df[df["t"] >= switch_t]
        diffs = np.abs(df_after["q_hat_window"] - target)
        idx = np.where(diffs < 0.05)[0]
        t_conv = int(df_after["t"].iloc[idx[0]]) if len(idx) else None
        rows.append((W, t_conv))
    return rows

def write_latex(mae, rows_b, rows_c, outfile="metrics_table.tex"):
    with open(outfile, "w") as f:
        f.write("% Auto-generated by make_metrics_table.py\n")
        f.write("\\begin{table}[h]\n\\centering\n")
        f.write("\\caption{Summary metrics for synthetic prototypes (strict/generalized matching and gestalt constraints).}\n")
        f.write("\\label{tab:lab_metrics}\n")

        # Part A
        f.write("\\begin{tabular}{l r}\n\\hline\n\\textbf{Part A: Strict matching (MLE)} & \\\\\n\\hline\n")
        f.write(f"Mean absolute error (MAE) & {mae:.4f} \\\\\n\\hline\n\\end{tabular}\n\\vspace{0.6em}\n\n")

        # Part B
        f.write("\\begin{tabular}{l r r r r}\n\\hline\n")
        f.write("\\textbf{Part B: Generalized matching} & $\\beta$ (set) & bias (set) & slope $\\hat{\\beta}$ & intercept $\\widehat{\\text{bias}}$ \\\\\n\\hline\n")
        for fn, beta, bias, slope, intercept in rows_b:
            f.write(f"{fn} & {beta:.2f} & {bias:.2f} & {slope:.2f} & {intercept:.2f} \\\\\n")
        f.write("\\hline\n\\end{tabular}\n\\vspace{0.6em}\n\n")

        # Part C
        f.write("\\begin{tabular}{r r}\n\\hline\n")
        f.write("\\textbf{Part C: Gestalt constraint (window)} & Convergence time (steps) \\\\\n\\hline\n")
        for W, t in rows_c:
            tdisp = f"{t}" if t is not None else "—"
            f.write(f"{W} & {tdisp} \\\\\n")
        f.write("\\hline\n\\end{tabular}\n\n\\end{table}\n")

if __name__ == "__main__":
    mae = part_a()
    rows_b = part_b()
    rows_c = part_c()
    write_latex(mae, rows_b, rows_c)
    print("Wrote metrics_table.tex")
